version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: app-postgres
    environment:
      POSTGRES_DB: chldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Changed to standard PostgreSQL port
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Spring Boot Backend
  backend:
    build: ./backend
    container_name: app-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chldb  # Fixed port
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_PROFILES_ACTIVE: dev  # Added profile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build: ./frontend
    container_name: app-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080  # Changed to use service name
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
