spring:
  application:
    name: Chl-Backend
  datasource:
    url: jdbc:postgresql://postgres:5432/chldb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        

server:
  port: 8080
  
# Logging to see what's happening
logging:
  level:
    com.yourpackage: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
